using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Authorization;

[GenerateTypedNameReferences]
public sealed partial class AuthPopup : Control
{
    public event Action? OnQuitPressed;
    public event Action? OnAcceptPressed;
    private string _url = string.Empty;

    public string URLText
    {
        get => _url;
        set
        {
            URL.Text = value;
            _url = value;
        }
    }

    public AuthPopup()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += OnAcceptButtonPressed;
        QuitButton.OnPressed += OnQuitButtonPressed;
    }

    private void OnQuitButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        OnQuitPressed?.Invoke();
    }

    private void OnAcceptButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        OnAcceptPressed?.Invoke();
    }
}
